import { BriefView } from "./view";
import { BriefStage } from "./schema";

/**
 * The brief as Markdown, because that is the format a writer actually pastes
 * into Notion, Docs or a CMS. Plain string building - a templating dependency
 * would be heavier than the thing it templates.
 */
export function briefToMarkdown(view: BriefView): string {
  const b = view.brief;
  const lines: string[] = [];
  const push = (...parts: string[]) => lines.push(...parts, "");
  const bullets = (items: string[]) => items.map((i) => `- ${i}`).join("\n");

  push(`# ${b.workingTitle}`);
  push(
    `> Content brief generated by MauSearch for **${view.keyword}** (${view.market}) · ${new Date(view.createdAt).toISOString().slice(0, 10)}`
  );

  push(`## Specification`);
  push(
    [
      `| Field | Value |`,
      `| --- | --- |`,
      `| Content type | ${b.contentType} |`,
      `| Word count | ${b.wordCount.min}–${b.wordCount.max} |`,
      `| Slug | \`/${b.slug}\` |`,
      `| H1 | ${b.metadata.h1} |`,
    ].join("\n")
  );

  push(`## 01 Objective`);
  push(
    [
      `**Business goal:** ${b.objective.businessGoal}`,
      `**Reader outcome:** ${b.objective.readerOutcome}`,
      `**Primary CTA:** ${b.objective.primaryCTA}`,
      `**Conversion path:** ${b.objective.conversionPath}`,
    ].join("\n\n")
  );

  push(`## 02 Editorial Directive`);
  push(`**Mandated hook:** ${b.editorialDirective.mandatedHook}`);
  push(`**Differentiation rule:** ${b.editorialDirective.differentiationRule}`);
  push(`**Tone and voice**\n${bullets(b.editorialDirective.toneAndVoice)}`);
  push(`**Must avoid**\n${bullets(b.editorialDirective.mustAvoid)}`);

  push(`## 03 Metadata`);
  push(
    [
      `- **Meta title** (${b.metadata.metaTitle.length} chars): ${b.metadata.metaTitle}`,
      `- **Meta description** (${b.metadata.metaDescription.length} chars): ${b.metadata.metaDescription}`,
      `- **H1:** ${b.metadata.h1}`,
    ].join("\n")
  );

  push(`## 04 Outline`);
  b.outline.forEach((section, index) => {
    lines.push(`### ${index + 1}. ${section.h2}  *(~${section.estWords} words)*`, "");
    lines.push(`*Purpose: ${section.purpose}*`, "");
    if (section.h3s.length > 0) lines.push(bullets(section.h3s.map((h) => `**${h}**`)), "");
    lines.push(bullets(section.talkingPoints), "");
    if (section.mandatoryAsset) lines.push(`> **Required asset:** ${section.mandatoryAsset}`, "");
  });

  if (b.faq.length > 0) {
    push(`## 05 FAQ`);
    push(b.faq.map((f) => `**${f.question}**\n\n${f.answerDirection}`).join("\n\n"));
  }

  push(`## 06 Internal Links & CTAs`);
  push(
    [
      `| Anchor | Target | Placement |`,
      `| --- | --- | --- |`,
      ...b.internalLinks.map((l) => `| ${l.anchor} | ${l.targetType} | ${l.placement} |`),
    ].join("\n")
  );

  push(`## 07 Assets Needed`);
  push(bullets(b.assetsNeeded.map((a) => `**${a.type}** — ${a.description}`)));

  push(`## 08 Entities to Cover`);
  push(b.entitiesToCover.map((e) => `\`${e}\``).join(" · "));

  push(`## 09 Writer Checklist`);
  push(b.writerChecklist.map((item) => `- [ ] ${item}`).join("\n"));

  push(`## 10 E-E-A-T Signals`);
  push(bullets(b.eeatSignals));

  push(`---`);
  push(`**Editor note:** ${b.editorNote}`);
  push(
    `*Produced by the MauSearch desk pipeline. Keyword data harvested from Google Suggest; ` +
      `strategy inferred by Nemotron. No search volume, CPC or keyword difficulty ` +
      `figures appear in this brief because MauSearch has no source for them.*`
  );

  return lines.join("\n").replace(/\n{3,}/g, "\n\n").trim() + "\n";
}

/**
 * What a section draft looks like with no live model: the outline itself,
 * already in the right markdown shape, so fixture mode shows the real flow
 * and a writer still gets something pasteable.
 */
export function sectionScaffold(section: BriefStage["outline"][number]): string {
  const lines = [`## ${section.h2}`, "", `_${section.purpose}_`, ""];
  for (const point of section.talkingPoints) lines.push(`- ${point}`);
  const perH3 = Math.round(section.estWords / Math.max(1, section.h3s.length));
  for (const h3 of section.h3s) {
    lines.push("", `### ${h3}`, "", `Draft ~${perH3} words covering this sub-topic.`);
  }
  if (section.mandatoryAsset) {
    lines.push("", `> Required asset: ${section.mandatoryAsset}`);
  }
  return lines.join("\n");
}

/** Free-tier models still fence their markdown now and then despite being told not to. */
export function stripCodeFence(text: string): string {
  return text
    .replace(/^\s*```(?:markdown|md)?[ \t]*\r?\n?/, "")
    .replace(/\r?\n?```\s*$/, "")
    .trim();
}
